export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';

export const CREATE_WORKER_SUCCESS = 'CREATE_WORKER_SUCCESS';
export const UPDATE_WORKER_SUCCESS = 'UPDATE_WORKER_SUCCESS';

export const CREATE_MANAGER_SUCCESS ='CREATE_MANAGER_SUCCESS';
export const UPDATE_MANAGER_SUCCESS ='UPDATE_MANAGER_SUCCESS';